/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programaprojeto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sueli
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        cmbEspecialidade = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 50, 16);

        jLabel2.setText("Login");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 50, 16);

        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 50, 16);

        jLabel4.setText("Especialidade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 120, 80, 16);
        getContentPane().add(txtNome);
        txtNome.setBounds(100, 30, 64, 22);
        getContentPane().add(txtLogin);
        txtLogin.setBounds(100, 60, 64, 22);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(100, 90, 64, 22);

        cmbEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Emergência", "Clinico geral", "Ortodontia", "Odonto pediatria", "Endodontia", "Periodontia", "Odontogeriatria", "Protese dentaria", "Implantodontia" }));
        getContentPane().add(cmbEspecialidade);
        cmbEspecialidade.setBounds(120, 120, 100, 22);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 170, 100, 23);

        setSize(new java.awt.Dimension(274, 295));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String n, l, s, e;
   n = txtNome.getText();
   l = txtLogin.getText();
   s = txtSenha.getText();
   e = cmbEspecialidade.getSelectedItem().toString();
   
   try{
   Class.forName("com.mysql.cj.jdbc.Driver");
   Connection conectado = DriverManager.getConnection
        ("jdbc:mysql://localhost:3306/projeto","root","admin");
   PreparedStatement st = conectado.prepareStatement
        ("INSERT INTO funcionarios(nome_funcionario,senha,login,especialidade) VALUES(?,?,?,?)");
   st.setString(1, n);
   st.setString(2, l);
   st.setString(3, s);
   st.setString(4, e);
   st.executeUpdate();
    JOptionPane.showMessageDialog(null, "Funcionário cadastrado com Sucesso");
   } catch (ClassNotFoundException ex){
        JOptionPane.showMessageDialog(null, "Driver mão colocado na library");
   } catch (SQLException ex){
        JOptionPane.showMessageDialog(null, "Erro nos dados do banco de dados" + ex.getMessage());}{
    }
    txtNome.setText("");
    txtLogin.setText("");
    txtSenha.setText("");
    cmbEspecialidade.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEspecialidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
