/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programaprojeto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sueli
 */
public class CadastrarPacientes extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPacientes
     */
    public CadastrarPacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCpf = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblIngredientes = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        brnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtCpf);
        txtCpf.setBounds(110, 120, 64, 22);

        lblCodigo.setText("Idade");
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(40, 80, 60, 16);

        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(40, 40, 60, 16);

        lblIngredientes.setText("Cpf");
        getContentPane().add(lblIngredientes);
        lblIngredientes.setBounds(40, 120, 60, 16);
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 40, 64, 22);
        getContentPane().add(txtIdade);
        txtIdade.setBounds(110, 80, 64, 22);

        brnSalvar.setText("Salvar");
        brnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(brnSalvar);
        brnSalvar.setBounds(70, 170, 72, 23);

        setSize(new java.awt.Dimension(254, 279));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void brnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnSalvarActionPerformed
        String n, i, c;
   n = txtNome.getText();
   i = txtIdade.getText();
   c = txtCpf.getText();
   
   try{
   Class.forName("com.mysql.cj.jdbc.Driver");
   Connection conectado = DriverManager.getConnection
        ("jdbc:mysql://localhost:3306/projeto","root","admin");
   PreparedStatement st = conectado.prepareStatement
        ("INSERT INTO pacientes(nome_paciente,idade,cpf) VALUES(?,?,?)");
   st.setString(1, n);
   st.setString(2, i);
   st.setString(3, c);
   st.executeUpdate();
    JOptionPane.showMessageDialog(null, "Paciente Cadastrado com Sucesso");
   } catch (ClassNotFoundException ex){
        JOptionPane.showMessageDialog(null, "Driver mão colocado na library");
   } catch (SQLException ex){
        JOptionPane.showMessageDialog(null, "Erro nos dados do banco de dados"+ ex.getMessage());}{
    }
    txtNome.setText("");
    txtIdade.setText("");
    txtCpf.setText("");
    }//GEN-LAST:event_brnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnSalvar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
